# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hedonometer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=400)),
                ('tweeted', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('votes', models.IntegerField()),
                ('winner', models.CharField(max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Book')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='MovieAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=400)),
                ('tweeted', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('votes', models.IntegerField()),
                ('winner', models.CharField(max_length=1)),
                ('window', models.CharField(max_length=6)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Movie')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='MovieVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.MovieAnnotation')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=200)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.Annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.TwitterProfile')),
            ],
        ),
        migrations.AddField(
            model_name='movievote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='movieannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twython_django.TwitterProfile'),
        ),
    ]
