# Generated by Django 3.0.5 on 2021-01-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0010_remove_embeddable_author'),
        ('twython_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieannotation',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieannotation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movievote',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='movievote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='MovieAnnotation',
        ),
        migrations.DeleteModel(
            name='MovieVote',
        ),
        migrations.DeleteModel(
            name='TwitterProfile',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
