# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twython_django', '0001_initial'),
        ('hedonometer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twython_django.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='band',
            name='albums',
            field=models.ManyToManyField(to='hedonometer.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='hedonometer.Song'),
        ),
    ]
