# Generated by Django 3.0 on 2020-04-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0002_auto_20200413_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='albums',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
