# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0003_auto_20200331_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeseries',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Timeseries', to_field='title'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='title',
            field=models.CharField(help_text='Title to use in the URL.', max_length=100, unique=True),
        ),
    ]
