# Generated by Django 3.0 on 2020-04-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0004_auto_20200414_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries',
            name='sumHappsFile',
        ),
    ]
