# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0004_auto_20200331_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(default='english', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='happs',
            name='timeseries',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Timeseries', to_field='title'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='sourceDir',
            field=models.CharField(default='/users/j/m/jminot/scratch/labmt/storywrangler_en', help_text='Directory on the VACC to pull daily vectors from.', max_length=200),
        ),
        migrations.AddField(
            model_name='word',
            name='word_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='happs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='googleBooksRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='lyricsRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='newYorkTimesRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='twitterRank',
            field=models.IntegerField(null=True),
        ),
    ]
