# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0005_auto_20200331_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='wordlist',
            field=models.ForeignKey(default=b'labMTenglish-v1', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.WordList', to_field=b'title'),
        ),
    ]
