# Generated by Django 3.0 on 2020-04-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0005_remove_timeseries_sumhappsfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries',
            name='language',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='scoreList',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='stopWordList',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='wordListEnglish',
        ),
        migrations.AddField(
            model_name='word',
            name='stopword',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='wordList',
            field=models.ForeignKey(default='labMT-en-v2', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.WordList', to_field='title'),
        ),
    ]
