# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0006_word_wordlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoHapps',
        ),
        migrations.RemoveField(
            model_name='happs',
            name='lang',
        ),
    ]
