# Generated by Django 3.0 on 2020-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0007_auto_20200414_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='showindropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='showindropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='showinfulllist',
            field=models.BooleanField(default=False),
        ),
    ]
