# Generated by Django 3.0 on 2020-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0008_auto_20200415_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='happs',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Exclude day from timeseries and api.'),
        ),
    ]
