# Generated by Django 2.2 on 2020-04-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0008_auto_20200401_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddable',
            name='nickName',
            field=models.CharField(default='My super wordshift.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.IntegerField(help_text='Centered at 0, higher numbers keep the event on the vizualization as you zoom out, lower numbers hide it earlier.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longer',
            field=models.TextField(help_text='Shows up in the description of the event inside shift popups (big and small).', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(default='world', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='shorter',
            field=models.CharField(help_text='Use commas to make new lines on the main visualization label.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeseries',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Timeseries', to_field='title'),
        ),
        migrations.AlterField(
            model_name='gutenbergbook',
            name='ignorewords',
            field=models.CharField(help_text='Comma separated list of words to ignore from this one.', max_length=400),
        ),
        migrations.AlterField(
            model_name='gutenbergbook',
            name='scaling_exponent',
            field=models.FloatField(blank=True, help_text='Zipf law fit scaling exponent.', null=True),
        ),
        migrations.AlterField(
            model_name='gutenbergbook',
            name='scaling_exponent_top100',
            field=models.FloatField(blank=True, help_text='The scaling exponent fit across just the top 100.', null=True),
        ),
        migrations.AlterField(
            model_name='happs',
            name='timeseries',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Timeseries', to_field='title'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='customLongTitle',
            field=models.CharField(default='Average Happiness for Twitter', help_text='Title on the webpage.', max_length=200),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='directory',
            field=models.CharField(help_text='Name of the directory for this particular time series.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='language',
            field=models.CharField(help_text='Second underlined part of the subtitle.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='mediaFlag',
            field=models.CharField(default='All tweets', help_text='Describe the type of data. First part of the subtitle.', max_length=50),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='scoreList',
            field=models.CharField(default='labMTscores-english-covid.csv', help_text='Name of the csv of scores.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='shiftDir',
            field=models.CharField(default='shifts', help_text='Directory name with daily pre-shifted word vectors (as subdir of `directory`).', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='sourceDir',
            field=models.CharField(default='/users/j/m/jminot/scratch/labmt/storywrangler_en', help_text='Directory on the VACC to pull daily vectors from.', max_length=200),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='stopWordList',
            field=models.CharField(blank=True, default='stopwords.csv', help_text='Name of the csv of words to exclude.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='sumHappsFile',
            field=models.CharField(default='sumhapps.csv', help_text='Name of the CSV with date,happs for the full time series.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='title',
            field=models.CharField(help_text='Title to use in the URL.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='wordList',
            field=models.CharField(default='labMTwords-english-covid.csv', help_text='Name of the csv of words.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='wordListEnglish',
            field=models.CharField(default='labMTwords-english-covid.csv', help_text='Name of the csv of words in English.', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='wordVecDir',
            field=models.CharField(default='word-vectors', help_text='Directory name with daily word vectors (as subdir of `directory`).', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='wordlist',
            field=models.ForeignKey(default='labMTenglish-v1', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.WordList', to_field='title'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
