# Generated by Django 3.0 on 2020-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0009_auto_20200402_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='happs',
            name='frequency',
            field=models.FloatField(default=0),
        ),
    ]
