# Generated by Django 3.0 on 2020-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0010_happs_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='event',
            name='region',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='x',
            field=models.IntegerField(help_text='x offset of annotation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='y',
            field=models.IntegerField(help_text='y offset of annotation'),
        ),
    ]
