# Generated by Django 3.0.5 on 2021-10-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0010_remove_embeddable_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embeddable',
        ),
    ]
