# Generated by Django 3.0 on 2020-04-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0011_auto_20200409_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='happs',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='hedonometer.Happs'),
            preserve_default=False,
        ),
    ]
