# Generated by Django 3.0 on 2020-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0012_event_happs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappsEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hedonometer.happs',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeseries',
        ),
        migrations.RemoveField(
            model_name='event',
            name='value',
        ),
    ]
