# Generated by Django 3.0.5 on 2020-04-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0013_auto_20200411_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='happs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='hedonometer.Happs'),
        ),
    ]
