# Generated by Django 3.0 on 2020-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0014_auto_20200411_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='event',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='word',
            name='googleBooksRank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='lyricsRank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='newYorkTimesRank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='twitterRank',
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='compFile',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='compFileName',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='contextFlag',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='customFullText',
            field=models.CharField(blank=True, default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='customTitleText',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='refFile',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='refFileName',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embeddable',
            name='stopWords',
            field=models.CharField(blank=True, default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gutenbergauthor',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gutenbergbook',
            name='excludeReason',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='excludeReason',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='ignorewords',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='reviews',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nyt',
            name='ignorewords',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='stopWordList',
            field=models.CharField(blank=True, default='stopwords.csv', help_text='Name of the csv of words to exclude.', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='word_english',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
