# Generated by Django 3.0 on 2020-04-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hedonometer', '0015_auto_20200413_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='reference',
            field=models.URLField(default='https://arxiv.org/abs/1406.3855'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordlist',
            name='referencetitle',
            field=models.CharField(default='this paper', max_length=300),
        ),
        migrations.AlterField(
            model_name='word',
            name='wordlist',
            field=models.ForeignKey(default='labMT-en-v1', on_delete=django.db.models.deletion.CASCADE, to='hedonometer.WordList', to_field='title'),
        ),
    ]
